"""CI workflow generator for ADR enforcement.

Generates GitHub Actions workflow YAML that runs ADR policy enforcement
checks on pull requests. The workflow:
- Runs `adr-kit enforce ci --format json`
- Fails the build on violations
- Posts structured PR comments for AI agents to self-correct
"""

from pathlib import Path

_MANAGED_HEADER = "# Auto-generated by ADR Kit — do not edit manually"


class CIWorkflowGenerator:
    """Generate GitHub Actions workflow for ADR enforcement."""

    def generate(self, output_path: Path | None = None) -> str:
        """Generate a GitHub Actions workflow YAML.

        Args:
            output_path: Where to write the file. If provided, writes to disk.
                Defaults to None (return content only).

        Returns:
            The workflow YAML content.

        Raises:
            FileExistsError: If output_path exists and wasn't generated by ADR Kit.
        """
        content = self._build_workflow()

        if output_path:
            self._safe_write(output_path, content)

        return content

    def _build_workflow(self) -> str:
        """Build the workflow YAML content."""
        return f"""{_MANAGED_HEADER}
# Regenerate: adr-kit generate-ci
name: ADR Enforcement

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  enforce:
    name: ADR Policy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install adr-kit
        run: pip install adr-kit

      - name: Run enforcement checks
        id: enforce
        run: |
          adr-kit enforce ci --format json > adr-report.json
          echo "exit_code=$?" >> "$GITHUB_OUTPUT"
        continue-on-error: true

      - name: Post PR comment
        if: always() && steps.enforce.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let report;
            try {{
              report = JSON.parse(fs.readFileSync('adr-report.json', 'utf8'));
            }} catch (e) {{
              report = {{ passed: false, violations: [], errors: ['Failed to parse report'] }};
            }}

            let body = '## ADR Enforcement Report\\n\\n';

            if (report.violations && report.violations.length > 0) {{
              body += '### Violations\\n\\n';
              for (const v of report.violations) {{
                const icon = v.severity === 'error' ? ':x:' : ':warning:';
                const loc = v.line ? `${{v.file}}:${{v.line}}` : v.file;
                body += `${{icon}} **${{v.adr_id}}**: ${{v.message}}\\n`;
                body += `  - Location: ` + '`' + `${{loc}}` + '`' + `\\n`;
                if (v.fix_suggestion) {{
                  body += `  - Fix: ${{v.fix_suggestion}}\\n`;
                }}
                body += '\\n';
              }}
            }}

            if (report.summary) {{
              body += `\\n**Summary**: ${{report.summary.error_count}} error(s), ${{report.summary.warning_count}} warning(s)\\n`;
            }}

            body += '\\n<details><summary>Raw JSON report</summary>\\n\\n```json\\n' + JSON.stringify(report, null, 2) + '\\n```\\n</details>';

            // Find existing comment to update
            const {{ data: comments }} = await github.rest.issues.listComments({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            }});
            const existing = comments.find(c => c.body.includes('## ADR Enforcement Report'));

            if (existing) {{
              await github.rest.issues.updateComment({{
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              }});
            }} else {{
              await github.rest.issues.createComment({{
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              }});
            }}

      - name: Fail on violations
        if: steps.enforce.outcome == 'failure'
        run: exit 1
"""

    def _safe_write(self, output_path: Path, content: str) -> None:
        """Write content, refusing to overwrite non-managed files."""
        if output_path.exists():
            existing = output_path.read_text(encoding="utf-8")
            if not existing.startswith(_MANAGED_HEADER):
                raise FileExistsError(
                    f"{output_path} exists and was not generated by ADR Kit. "
                    f"Remove it manually or add '{_MANAGED_HEADER}' as the first line."
                )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
