"""Standalone validation script generator.

Generates stdlib-only Python scripts from ADR policies. Each script:
- Checks one ADR's policies against source files
- Outputs JSON matching the EnforcementReport schema (reporter.py)
- Supports --quick (git changed files) and --full (all files) modes
- Requires no adr-kit installation at runtime

Also generates a validate_all.py runner that aggregates results.
"""

import stat
from pathlib import Path

from ..core.model import ADR, ADRStatus
from ..core.parse import ParseError, find_adr_files, parse_adr_file
from .stages import StagedCheck, classify_adr_checks


class ScriptGenerator:
    """Generate standalone validation scripts from ADR policies."""

    def __init__(self, adr_dir: str | Path = "docs/adr") -> None:
        self.adr_dir = Path(adr_dir)

    def generate_for_adr(self, adr: ADR, output_dir: Path) -> Path | None:
        """Generate a validation script for a single ADR.

        Returns:
            Path to the generated script, or None if ADR has no enforceable policies.
        """
        checks = classify_adr_checks([adr])
        # Skip config checks — they need TOML/JSON parsing not yet implemented
        enforceable = [c for c in checks if c.check_type != "config"]
        if not enforceable:
            return None

        script = self._build_script(adr, enforceable)
        if not script:
            return None

        output_dir.mkdir(parents=True, exist_ok=True)
        safe_id = adr.id.lower().replace("-", "_")
        script_path = output_dir / f"validate_{safe_id}.py"
        script_path.write_text(script, encoding="utf-8")
        script_path.chmod(
            script_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH
        )

        return script_path

    def generate_all(self, output_dir: Path) -> list[Path]:
        """Generate scripts for all accepted ADRs and a runner.

        Returns:
            List of all generated file paths (individual scripts + runner).
        """
        adrs = self._load_accepted_adrs()
        paths: list[Path] = []

        for adr in adrs:
            path = self.generate_for_adr(adr, output_dir)
            if path:
                paths.append(path)

        runner = self._generate_runner_script(output_dir)
        paths.append(runner)

        return paths

    # --- Script building ---

    def _build_script(self, adr: ADR, checks: list[StagedCheck]) -> str:
        """Build the complete script content for an ADR."""
        adr_id = _escape(adr.id)
        adr_title = _escape(adr.title)

        check_functions: list[str] = []
        check_calls: list[str] = []

        for i, check in enumerate(checks):
            func_name = f"check_{i}"
            func_code = self._generate_check_function(func_name, check)
            if func_code:
                check_functions.append(func_code)
                check_calls.append(func_name)

        if not check_functions:
            return ""

        checks_code = "\n\n\n".join(check_functions)
        calls_code = "\n".join(
            f"    violations.extend({name}(files))" for name in check_calls
        )
        num_checks = len(check_calls)

        return f'''\
#!/usr/bin/env python3
"""{adr_id} validation: {adr_title}

Auto-generated by ADR Kit. Regenerate: adr-kit generate-scripts
"""

import argparse
import fnmatch
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ADR_ID = "{adr_id}"
ADR_TITLE = "{adr_title}"

SOURCE_EXTENSIONS = {{".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".go", ".rs", ".kt"}}

EXCLUDE_DIRS = {{
    ".git", ".venv", "venv", "node_modules", "__pycache__",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", "dist", "build",
    ".adr-kit", ".project-index",
}}


def get_files(mode, project_root="."):
    """Collect files based on mode."""
    root = Path(project_root)

    if mode == "quick":
        try:
            result = subprocess.run(
                ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
                capture_output=True, text=True, cwd=root,
            )
            if result.returncode == 0:
                files = [root / f for f in result.stdout.strip().splitlines() if f]
                return [f for f in files if f.exists() and f.suffix in SOURCE_EXTENSIONS]
        except FileNotFoundError:
            print("Warning: git not available, falling back to full scan", file=sys.stderr)

    files = []
    for f in root.rglob("*"):
        if not f.is_file():
            continue
        if f.suffix not in SOURCE_EXTENSIONS:
            continue
        if any(part in EXCLUDE_DIRS for part in f.parts):
            continue
        files.append(f)
    return files


{checks_code}


def main():
    parser = argparse.ArgumentParser(description=f"Validate {{ADR_ID}}: {{ADR_TITLE}}")
    parser.add_argument("--quick", action="store_true", help="Check staged/changed files only")
    parser.add_argument("--full", action="store_true", default=True, help="Check all files (default)")
    parser.add_argument("--root", default=".", help="Project root directory")
    args = parser.parse_args()

    mode = "quick" if args.quick else "full"
    project_root = Path(args.root).resolve()
    files = get_files(mode, project_root)

    violations = []
{calls_code}

    error_count = sum(1 for v in violations if v["severity"] == "error")
    warning_count = sum(1 for v in violations if v["severity"] == "warning")

    report = {{
        "schema_version": "1.0",
        "level": "ci",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "passed": error_count == 0,
        "summary": {{
            "files_checked": len(files),
            "checks_run": {num_checks},
            "error_count": error_count,
            "warning_count": warning_count,
        }},
        "violations": violations,
        "errors": [],
    }}

    print(json.dumps(report, indent=2))
    sys.exit(0 if report["passed"] else 1)


if __name__ == "__main__":
    main()
'''

    def _generate_check_function(
        self, func_name: str, check: StagedCheck
    ) -> str | None:
        """Generate a check function for a single StagedCheck."""
        if check.check_type in ("import", "python_import"):
            return self._generate_import_check(func_name, check)
        elif check.check_type == "pattern":
            return self._generate_pattern_check(func_name, check)
        elif check.check_type == "architecture":
            return self._generate_architecture_check(func_name, check)
        elif check.check_type == "required_structure":
            return self._generate_structure_check(func_name, check)
        return None

    def _generate_import_check(self, func_name: str, check: StagedCheck) -> str:
        """Generate code for an import restriction check."""
        if check.check_type == "python_import":
            filter_line = '    target_files = [f for f in files if f.suffix == ".py"]'
        else:
            filter_line = (
                "    target_files = [f for f in files if f.suffix in "
                '{".js", ".ts", ".jsx", ".tsx"}]'
            )

        lib = _escape(check.pattern)
        adr_id = _escape(check.adr_id)
        severity = _escape(check.severity)
        message = _escape(check.message)
        adr_title = _escape(check.adr_title or "")
        level = _escape(check.level.value)

        return f'''\
def {func_name}(files):
    """From {adr_id}: import check for '{lib}'"""
{filter_line}
    violations = []
    escaped = re.escape("{lib}")
    _q = "[" + chr(39) + chr(34) + "]"
    _nq = "[^" + chr(39) + chr(34) + "]*?"
    import_patterns = [
        re.compile(r"(from|import)\\s+" + escaped + r"(\\.|\\s|$|;)"),
        re.compile(r"(import|from)\\s+" + _q + r"(" + _nq + r"/)?" + escaped + _q),
        re.compile(r"require\\s*\\(\\s*" + _q + r"(" + _nq + r"/)?" + escaped + _q + r"\\s*\\)"),
    ]
    for file_path in target_files:
        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
            for line_num, line in enumerate(content.splitlines(), 1):
                for pattern in import_patterns:
                    if pattern.search(line):
                        violations.append({{
                            "file": str(file_path),
                            "line": line_num,
                            "adr_id": "{adr_id}",
                            "adr_title": "{adr_title}",
                            "message": "{message}",
                            "severity": "{severity}",
                            "level": "{level}",
                            "fix_suggestion": "Remove or replace this import — see {adr_id}",
                        }})
                        break
        except Exception:
            continue
    return violations'''

    def _generate_pattern_check(self, func_name: str, check: StagedCheck) -> str:
        """Generate code for a regex pattern check."""
        # Only escape quotes — pattern goes in r"..." where backslashes are literal
        pattern_escaped = check.pattern.replace('"', '\\"')
        adr_id = _escape(check.adr_id)
        severity = _escape(check.severity)
        message = _escape(check.message)
        adr_title = _escape(check.adr_title or "")
        level = _escape(check.level.value)

        if check.file_glob and check.file_glob.startswith("*."):
            ext = check.file_glob[1:]
            filter_line = (
                f'    target_files = [f for f in files if f.name.endswith("{ext}")]'
            )
        else:
            filter_line = "    target_files = files"

        return f'''\
def {func_name}(files):
    """From {adr_id}: pattern check"""
{filter_line}
    violations = []
    try:
        compiled = re.compile(r"{pattern_escaped}")
    except re.error:
        return []
    for file_path in target_files:
        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
            for line_num, line in enumerate(content.splitlines(), 1):
                if compiled.search(line):
                    violations.append({{
                        "file": str(file_path),
                        "line": line_num,
                        "adr_id": "{adr_id}",
                        "adr_title": "{adr_title}",
                        "message": "{message}",
                        "severity": "{severity}",
                        "level": "{level}",
                        "fix_suggestion": None,
                    }})
        except Exception:
            continue
    return violations'''

    def _generate_architecture_check(self, func_name: str, check: StagedCheck) -> str:
        """Generate code for an architecture layer boundary check."""
        parts = check.pattern.split("->")
        if len(parts) != 2:
            return ""
        source_layer = parts[0].strip().lower()
        target_layer = parts[1].strip().lower()
        if not source_layer or not target_layer:
            return ""

        check_glob = _escape(check.metadata.get("check", ""))
        adr_id = _escape(check.adr_id)
        severity = _escape(check.severity)
        message = _escape(check.message)
        adr_title = _escape(check.adr_title or "")
        level = _escape(check.level.value)

        return f'''\
def {func_name}(files):
    """From {adr_id}: architecture check '{source_layer} -> {target_layer}'"""
    source_layer = "{source_layer}"
    target_layer = "{target_layer}"
    check_glob = "{check_glob}"
    violations = []

    if check_glob:
        # Extract directory prefix from glob (e.g., "ui/**/*.py" -> "ui")
        glob_dir = check_glob.split("/")[0].lower() if "/" in check_glob else check_glob.lower()
        glob_ext = None
        if check_glob.endswith(".py"):
            glob_ext = ".py"
        elif check_glob.endswith(".ts") or check_glob.endswith(".tsx"):
            glob_ext = (".ts", ".tsx")
        elif check_glob.endswith(".js") or check_glob.endswith(".jsx"):
            glob_ext = (".js", ".jsx")
        source_files = []
        for f in files:
            if glob_dir not in [p.lower() for p in f.parts]:
                continue
            if glob_ext and not f.suffix in (glob_ext if isinstance(glob_ext, tuple) else (glob_ext,)):
                continue
            source_files.append(f)
    else:
        source_files = [f for f in files if source_layer in [p.lower() for p in f.parts]]

    escaped = re.escape(target_layer)
    _q = "[" + chr(39) + chr(34) + "]"
    _nq = "[^" + chr(39) + chr(34) + "]*?"
    target_patterns = [
        re.compile(r"(from|import)\\s+" + escaped + r"(\\.\\w+)*(\\s|$|;)", re.IGNORECASE),
        re.compile(r"(import|from)\\s+" + _q + r"(" + _nq + r"[/\\\\])?" + escaped + r"([/\\\\]" + _nq + r")?" + _q, re.IGNORECASE),
        re.compile(r"require\\s*\\(\\s*" + _q + r"(" + _nq + r"[/\\\\])?" + escaped + r"([/\\\\]" + _nq + r")?" + _q + r"\\s*\\)", re.IGNORECASE),
    ]

    for file_path in source_files:
        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
            for line_num, line in enumerate(content.splitlines(), 1):
                for pattern in target_patterns:
                    if pattern.search(line):
                        violations.append({{
                            "file": str(file_path),
                            "line": line_num,
                            "adr_id": "{adr_id}",
                            "adr_title": "{adr_title}",
                            "message": "{message}",
                            "severity": "{severity}",
                            "level": "{level}",
                            "fix_suggestion": "Move this import out of " + source_layer + " code — see {adr_id}",
                        }})
                        break
        except Exception:
            continue
    return violations'''

    def _generate_structure_check(self, func_name: str, check: StagedCheck) -> str:
        """Generate code for a required structure check."""
        adr_id = _escape(check.adr_id)
        severity = _escape(check.severity)
        message = _escape(check.message)
        adr_title = _escape(check.adr_title or "")
        level = _escape(check.level.value)
        pattern = _escape(check.pattern)

        return f'''\
def {func_name}(files):
    """From {adr_id}: required structure '{check.pattern}'"""
    import glob as glob_mod
    matches = list(glob_mod.glob("{pattern}"))
    if not matches:
        return [{{
            "file": "{pattern}",
            "line": None,
            "adr_id": "{adr_id}",
            "adr_title": "{adr_title}",
            "message": "{message}",
            "severity": "{severity}",
            "level": "{level}",
            "fix_suggestion": "Create the required path: {pattern} — see {adr_id}",
        }}]
    return []'''

    def _generate_runner_script(self, output_dir: Path) -> Path:
        """Generate validate_all.py that runs all individual scripts and aggregates."""
        output_dir.mkdir(parents=True, exist_ok=True)
        runner_path = output_dir / "validate_all.py"

        runner = '''\
#!/usr/bin/env python3
"""Run all ADR validation scripts and aggregate results.

Auto-generated by ADR Kit. Regenerate: adr-kit generate-scripts
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Run all ADR validation scripts")
    parser.add_argument("--quick", action="store_true", help="Check staged/changed files only")
    parser.add_argument("--full", action="store_true", default=True, help="Check all files (default)")
    parser.add_argument("--root", default=".", help="Project root directory")
    args = parser.parse_args()

    mode_flag = "--quick" if args.quick else "--full"
    script_dir = Path(__file__).parent

    scripts = sorted(script_dir.glob("validate_adr_*.py"))

    total_files = 0
    total_checks = 0
    total_errors = 0
    total_warnings = 0
    all_violations = []
    all_errors = []
    passed = True

    for script in scripts:
        try:
            result = subprocess.run(
                [sys.executable, str(script), mode_flag, "--root", args.root],
                capture_output=True, text=True,
            )
            if result.stdout.strip():
                report = json.loads(result.stdout)
                total_files = max(total_files, report["summary"]["files_checked"])
                total_checks += report["summary"]["checks_run"]
                total_errors += report["summary"]["error_count"]
                total_warnings += report["summary"]["warning_count"]
                all_violations.extend(report.get("violations", []))
                all_errors.extend(report.get("errors", []))
                if not report["passed"]:
                    passed = False
            elif result.returncode != 0:
                all_errors.append(f"Script {script.name} failed: {result.stderr.strip()}")
                passed = False
        except json.JSONDecodeError:
            all_errors.append(f"Script {script.name} produced invalid JSON")
        except Exception as e:
            all_errors.append(f"Script {script.name} error: {e}")

    merged = {
        "schema_version": "1.0",
        "level": "ci",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "passed": passed,
        "summary": {
            "files_checked": total_files,
            "checks_run": total_checks,
            "error_count": total_errors,
            "warning_count": total_warnings,
        },
        "violations": all_violations,
        "errors": all_errors,
    }

    print(json.dumps(merged, indent=2))
    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
'''

        runner_path.write_text(runner, encoding="utf-8")
        runner_path.chmod(
            runner_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH
        )

        return runner_path

    # --- Helpers ---

    def _load_accepted_adrs(self) -> list[ADR]:
        adrs: list[ADR] = []
        if not self.adr_dir.exists():
            return adrs
        for file_path in find_adr_files(self.adr_dir):
            try:
                adr = parse_adr_file(file_path, strict=False)
                if adr and adr.front_matter.status == ADRStatus.ACCEPTED:
                    adrs.append(adr)
            except ParseError:
                continue
        return adrs


def _escape(value: str) -> str:
    """Escape a string for safe embedding in generated Python code."""
    return value.replace("\\", "\\\\").replace('"', '\\"')
